import json
import tempfile
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from src.api.server import app
from src.providers.ingredient_provider import IngredientDataProvider
from src.data_layer.recipe_db import RecipeDB


class DummyLLMClient:
    """Mock LLM boundary: returns deterministic RecipeDraftEnvelope JSON."""

    def generate_json(self, *, system_prompt, user_prompt, schema_name, temperature=0.0):
        assert schema_name == "RecipeDraftEnvelope"
        assert temperature == 0.0
        return {
            "drafts": [
                {
                    "name": "Generated by LLM",
                    "ingredients": [
                        {"name": "chicken breast", "quantity": 200.0, "unit": "g"},
                        {"name": "white rice", "quantity": 250.0, "unit": "g"},
                    ],
                    "instructions": ["Cook it.", "Serve it."],
                }
            ]
        }


class FakeUSDAProvider(IngredientDataProvider):
    """Mock USDA-backed provider boundary (validation + nutrition recomputation)."""

    usda_capable = True

    def __init__(self):
        self._by_name = {
            "chicken breast": {
                "calories": 165.0,
                "protein_g": 31.0,
                "fat_g": 3.6,
                "carbs_g": 0.0,
            },
            "white rice": {
                "calories": 130.0,
                "protein_g": 2.7,
                "fat_g": 0.3,
                "carbs_g": 28.0,
            },
        }

    def get_ingredient_info(self, name: str):
        key = str(name).lower().strip()
        if key not in self._by_name:
            return None
        return {"name": key, "per_100g": self._by_name[key]}

    def resolve_all(self, ingredient_names):
        return None


def test_generate_validated_recipes_realistic_integration(monkeypatch):
    # Patch only API factories; run the full pipeline with fake LLM/provider boundaries.
    with tempfile.TemporaryDirectory() as td:
        recipes_path = str(Path(td) / "recipes.json")
        Path(recipes_path).write_text(json.dumps({"recipes": []}), encoding="utf-8")

        monkeypatch.setattr("src.api.server.recipes_path", recipes_path)
        monkeypatch.setattr("src.api.server.build_llm_client", lambda: DummyLLMClient())
        monkeypatch.setattr("src.api.server.build_usda_provider", lambda: FakeUSDAProvider())

        client = TestClient(app)
        resp = client.post(
            "/api/recipes/generate-validated",
            json={"context": {"x": 1}, "count": 1},
        )

        assert resp.status_code == 200
        data = resp.json()
        assert data["accepted_count"] == 1
        assert data["rejected_count"] == 0
        assert len(data["recipe_ids"]) == 1
        assert data["failures"] == []

        persisted = RecipeDB(recipes_path).get_all_recipes()
        assert any(r.id == data["recipe_ids"][0] for r in persisted)


def test_generate_validated_recipes_rejects_invalid_count(monkeypatch):
    client = TestClient(app)
    resp = client.post(
        "/api/recipes/generate-validated",
        json={"context": {}, "count": 0},
    )
    assert resp.status_code == 400
    assert resp.json() == {
        "error": {"code": "INVALID_REQUEST", "message": "Invalid request schema."}
    }


def test_generate_validated_recipes_rejects_missing_context(monkeypatch):
    client = TestClient(app)
    resp = client.post(
        "/api/recipes/generate-validated",
        json={"count": 1},
    )
    assert resp.status_code == 400
    assert resp.json() == {
        "error": {"code": "INVALID_REQUEST", "message": "Invalid request schema."}
    }

