/* global React, cx, RECIPE_BY, gradFor, recipeImg, Icon */
const Ds = window.MACROVA_DATA;

function DetailSheet({ recipe, meal, onClose, onPin, onEdit }) {
  if (!recipe) return null;
  const r = recipe;
  const isMeal = !!meal;
  const ings = [
    ["350 g", "spaghetti squash", "120 kcal"],
    ["350 g", "tomato", "63 kcal"],
    ["25 g", "parmesan cheese", "98 kcal"],
    ["10 g", "fresh parsley", "4 kcal"],
    ["140 g", "lean ground beef 95%", "195 kcal"],
  ];
  const steps = [
    "Halve the spaghetti squash; roast cut-side down at 400°F for 35 minutes until tender.",
    "While squash roasts, sauté the lean beef in a wide pan until browned. Add tomato; simmer 10 minutes.",
    "Scrape the squash flesh into long strands.",
    "Top with the meat sauce, fresh parsley, and grated parmesan.",
  ];
  return (
    <>
      <div className="scrim" onClick={onClose}/>
      <div className="sheet">
        <div className="sheet-hero" style={{ background: gradFor(r.id) }}>
          <button className="back" onClick={onClose}>‹</button>
          <button className="heart">♡</button>
        </div>
        <div className="sheet-body">
          <div className="row gap-sm" style={{ flexWrap: "wrap", marginBottom: 8 }}>
            {r.tags.slice(0, 3).map(t => <span key={t} className="tag">{t}</span>)}
          </div>
          <h1>{r.name}</h1>
          <div className="meta"><span>{r.time} min</span><span className="dot"/><span>1 serving</span><span className="dot"/><span>{r.kcal} kcal</span></div>

          {isMeal && (
            <div className={cx("attribution", meal.pinned && "pinned")}>
              <span className="ic"/>
              {meal.pinned ? <>Pinned by you · scheduled for Day {meal.dayIndex}, meal {meal.idx}</> : <>Generated by Macrova for Day {meal.dayIndex}, meal {meal.idx}</>}
            </div>
          )}

          {r.desc && <p style={{ margin: "0 0 18px", color: "var(--ink-2)", fontSize: 15, lineHeight: 1.55 }}>{r.desc}</p>}

          <div className="divider"/>
          <h3 className="sec-h">Nutrition per serving</h3>
          <div className="macro-grid">
            <div className="macro-cell"><div className="l">Calories</div><div className="v">{r.kcal}</div><div className="bar"><span style={{ width: Math.min(100, r.kcal / 750 * 100) + "%" }}/></div></div>
            <div className="macro-cell"><div className="l">Protein</div><div className="v">{r.p}<span className="u"> g</span></div><div className="bar"><span className="pro" style={{ width: Math.min(100, r.p / 50 * 100) + "%" }}/></div></div>
            <div className="macro-cell"><div className="l">Carbs</div><div className="v">{r.c}<span className="u"> g</span></div><div className="bar"><span className="carb" style={{ width: Math.min(100, r.c / 100 * 100) + "%" }}/></div></div>
            <div className="macro-cell"><div className="l">Fat</div><div className="v">{r.f}<span className="u"> g</span></div><div className="bar"><span className="fat" style={{ width: Math.min(100, r.f / 35 * 100) + "%" }}/></div></div>
          </div>

          <div className="divider"/>
          <h3 className="sec-h">Ingredients</h3>
          <p className="sec-sub">5 items · resolved from your local catalog</p>
          <div className="ing-list">
            {ings.map(([qty, name, kcal]) => (
              <div key={name} className="ing"><div className="qty">{qty}</div><div className="name">{name}</div><div className="kcal">{kcal}</div></div>
            ))}
          </div>

          <div className="divider"/>
          <h3 className="sec-h">Instructions</h3>
          <div>
            {steps.map((s, i) => (
              <div key={i} className="step"><div className="num">{i + 1}</div><p>{s}</p></div>
            ))}
          </div>

          {isMeal && (
            <>
              <div className="divider"/>
              <h3 className="sec-h">Why this slot?</h3>
              <p style={{ color: "var(--ink-2)", fontSize: 14, lineHeight: 1.6 }}>
                Selected because it matches busyness {meal.busyness}/4, contributes {r.p}g protein toward your weekly target, contains no peanuts or shellfish, and re-uses ingredients from earlier in the week.
              </p>
            </>
          )}

          <div className="divider"/>
          <details className="disclose">
            <summary>Tags &amp; categorization</summary>
            <div className="body">
              <div className="row gap-sm" style={{ flexWrap: "wrap", marginBottom: 10 }}>{r.tags.map(t => <span key={t} className="tag">{t}</span>)}</div>
              <p className="muted" style={{ fontSize: 13, margin: 0 }}>Read-only · tag editing is a planned addition.</p>
            </div>
          </details>
          <details className="disclose">
            <summary>Used in your plans</summary>
            <div className="body"><p className="muted" style={{ fontSize: 14, margin: 0 }}>Scheduled <b style={{ color: "var(--ink-1)" }}>1×</b> this week. Last cooked 11 days ago.</p></div>
          </details>
        </div>

        <div className="sticky-cta">
          {isMeal ? (
            <>
              <button className="btn flex-1" onClick={onPin}>{meal.pinned ? "Unpin" : "Pin meal"}</button>
              <button className="btn flex-1">Swap</button>
              <button className="btn btn-primary flex-1">Mark cooked</button>
            </>
          ) : (
            <>
              <button className="btn flex-1" onClick={onEdit}>Edit recipe</button>
              <button className="btn btn-primary flex-1">Add to plan</button>
            </>
          )}
        </div>
      </div>
    </>
  );
}

window.DetailSheet = DetailSheet;
